import Link from "next/link";

export default function GalleryPage() {
    return (
        <div className="absolute inset-0 h-full w-full bg-black bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]">
            <div className="absolute inset-0 flex flex-col items-center justify-center">
                <h1 className="text-4xl text-white font-bold mb-6">SVG Gallery</h1>
                <p className="text-white mb-4">Explore a collection of SVG icons generated by AI.</p>
                <p className="text-white">Gallery content will be here soon!</p>
                <Link href="/" className="text-green-500 underline">Back to Home</Link>
            </div>
        </div>
    )
}